cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - test_prod

build:
  stage: build
  script:
    - docker build -t hung/testcafe .
    - npm install

test_api_staging:
  stage: test
  script:
    - docker run --rm -i -e NODE_ENV=staging -v `pwd`/:/home/tester -u `stat -c "%u:%g" /home/tester` hung/testcafe npm run test_api_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_api.xml
  except:
    - schedules

test_chromium_staging:
  stage: test
  script:
    - docker run --rm -i -e NODE_ENV=staging -v `pwd`/:/home/tester -u `stat -c "%u:%g" /home/tester` hung/testcafe npm run test_chromium_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_chromium.xml
  except:
    - schedules

# test_firefox_staging:
#   stage: test
#   script:
#     - docker run --rm -i -e NODE_ENV=staging -v `pwd`/:/home/tester -u `stat -c "%u:%g" /home/tester` hung/testcafe npm run test_firefox_ci
#   artifacts:
#     expire_in: 1 week
#     reports:
#       junit: report/junit_firefox.xml
#   except:
#     - schedules

# test_mobile_emu_staging:
#   stage: test
#   script:
#     - docker run --rm -i -e NODE_ENV=staging -v `pwd`/:/home/tester hung/testcafe npm run test_mobile_emu_ci
#   artifacts:
#     expire_in: 1 week
#     reports:
#       junit: report/junit_mobile_emu.xml
#   except:
#     - schedules

test_api_prod:
  stage: test_prod
  script:
    - docker run --rm -i -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_api_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_api.xml
  only:
    - schedules

test_chromium_prod:
  stage: test_prod
  script:
    - docker run --rm -i -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_chromium_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_chromium.xml
  only:
    - schedules

# test_firefox_prod:
#   stage: test_prod
#   script:
#     - docker run --rm -i -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_firefox_ci
#   artifacts:
#     expire_in: 1 week
#     reports:
#       junit: report/junit_firefox.xml
#   only:
#     - schedules

# test_mobile_emu_prod:
#   stage: test_prod
#   script:
#     - docker run --rm -i -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_mobile_emu_ci
#   artifacts:
#     expire_in: 1 week
#     reports:
#       junit: report/junit_mobile_emu.xml
#   only:
#     - schedules    