stages:
  - build
  - test
  - test_prod
  - cleanup

build:
  stage: build
  script:
    - docker build -t hung/testcafe .

test_api:
  stage: test
  script:
    - docker run --rm -it -e NODE_ENV=staging -v `pwd`/:/home/tester hung/testcafe npm run test_api_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_api.xml
  except:
    - schedules

test_chromium:
  stage: test
  script:
    - docker run --rm -it -e NODE_ENV=staging -v `pwd`/:/home/tester hung/testcafe npm run test_chromium_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_chromium.xml
  except:
    - schedules

test_firefox:
  stage: test
  script:
    - docker run --rm -it -e NODE_ENV=staging -v `pwd`/:/home/tester hung/testcafe npm run test_firefox_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_firefox.xml
  except:
    - schedules

# test_mobile_emu:
#   stage: test
#   script:
#     - docker run --rm -it -e NODE_ENV=staging -v `pwd`/:/home/tester hung/testcafe npm run test_mobile_emu_ci
#   artifacts:
#     expire_in: 1 week
#     reports:
#       junit: report/junit_mobile_emu.xml
#   except:
#     - schedules

test_api:
  stage: test_prod
  script:
    - docker run --rm -it -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_api_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_api.xml
  only:
    - schedules

test_chromium:
  stage: test_prod
  script:
    - docker run --rm -it -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_chromium_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_chromium.xml
  only:
    - schedules

test_firefox:
  stage: test_prod
  script:
    - docker run --rm -it -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_firefox_ci
  artifacts:
    expire_in: 1 week
    reports:
      junit: report/junit_firefox.xml
  only:
    - schedules

# test_mobile_emu:
#   stage: test_prod
#   script:
#     - docker run --rm -it -e NODE_ENV=production -v `pwd`/:/home/tester hung/testcafe npm run test_mobile_emu_ci
#   artifacts:
#     expire_in: 1 week
#     reports:
#       junit: report/junit_mobile_emu.xml
#   only:
#     - schedules    

cleanup:
  stage: cleanup
  script:
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  when: always